#cloud-config
packages:
  - build-essential
  - wget
  - curl
  - htop
  - tmux
  - tar
  - gzip
  - git
  - openjdk-8-jre # Java 8 for Tassel
  - r-base # R and R development
  - r-base-dev

users:
  - name: futurebees
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEAZR2qFp/1DYB6g7ixKpQhiMxV+HIh9pn/yJic7XiWJ
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash

runcmd:
  # Install Docker 
  - curl -fsSL https://get.docker.com | sh
  
  # Install Tassel
  - mkdir -p /opt/tassel
  - git clone https://bitbucket.org/tasseladmin/tassel-5-standalone/ /opt/tassel

  # Install BWA
  - wget "https://newcontinuum.dl.sourceforge.net/project/bio-bwa/bwa-0.7.17.tar.bz2"
  - tar -xjvf bwa-0.7.17.tar.bz2
  - cd bwa-0.7.17 && make && cd

  # Download KGD 
  - git clone https://github.com/AgResearch/KGD
  
